### ISSUE TITLE
Action fails while running on master/main

### ISSUE THREAD

**Issue by maxmcd** [neofinancial/ticket-check-action#18]
Hello. First off we use this action at @voltusdev, thanks for making it.

When we merge PRs, it seems like the PR action still runs, even when the PR is closed. We get the following error message:
```
Could not retrieve the Pull Request body
```

I was able to solve this by adding an if check to the run stanza:
```
      - name: Check for ticket
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: neofinancial/ticket-check-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

I can't tell if this is expected, or maybe the error is because we auto-delete our branches, or maybe it's a bug with this check (but if it is, I wonder why I'm the first to experience it).

Any thoughts on this issue? 

(here's the full text of our config, if that's helpful)
```
name: PR Ticket Check

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  status: {}
jobs:
  ticket-check:
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run: env
      - name: Check for ticket
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: neofinancial/ticket-check-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ticketLink: 'https://github.com/voltusdev/voltus/issues/%ticketNumber%'
          ticketPrefix: '#'
          titleRegex: '^#(?<ticketNumber>\d+)'
          branchRegex: '^(?<ticketNumber>\d+)'
          bodyRegex: '#(?<ticketNumber>\d+)'
          bodyURLRegex: 'http(s?):\/\/(github.com)(\/voltusdev)(\/voltus)(\/issues)\/(?<ticketNumber>\d+)'
          exemptUsers: dependabot
```
