### ISSUE TITLE
Support for monorepo

### ISSUE THREAD

**Issue by cyrus-za** [neofinancial/ticket-check-action#19]
We running a monorepo and thus got a jira board for each project. The regex part can be figured out manually if need be, but the ticket-link and ticket-prefix needs to be dynamicly set. 

Maybe something like in our PR template we add 

```md
## Project

- [ ] DS (Design System)
- [ ] AD (Admin Dashboard
- [ ] POR (Client Portal)
```

Which will render 
## Project

- [ ] DS (Design System)
- [ ] AD (Admin Dashboard
- [ ] POR (Client Portal)

Then based on what gets checked, it will use that prefix?

If that won't work, maybe a way to generically check for a ticket number provided in title or something and use that. 

I am open for ideas

**Comment by cyrus-za** [comment]
I figured out a workaround for now. Going to leave this open until the maintainer replies, though.

## Workaround

Create multiple yml files and use `paths` option.

e.g.

```yml
# .github/workflows/ticket-check-ui

name: Pull Request Description

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    paths:
      - 'libs/ui/**'

jobs:
  jira_ticket:
    name: jira ticket check
    runs-on: ubuntu-latest

    steps:
      - name: Check jira for ticket
        uses: neofinancial/ticket-check-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ticketLink: 'https://invisible.atlassian.net/browse/DS-%ticketNumber%'
          ticketPrefix: 'DS-'
          titleRegex: '^DS-(?<ticketNumber>\d+)'
          branchRegex: '^DS-(?<ticketNumber>\d+)'
          bodyRegex: 'DS-(?<ticketNumber>\d+)'
          bodyURLRegex: 'http(s?):\/\/(invisible.atlassian.net)(\/browse)\/(DS\-)(?<ticketNumber>\d+)'
```

```yml
# .github/workflows/ticket-check-portal
name: Pull Request Description

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    paths:
      - 'libs/portal/**'

jobs:
  jira_ticket:
    name: jira ticket check
    runs-on: ubuntu-latest

    steps:
      - name: Check jira for ticket
        uses: neofinancial/ticket-check-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ticketLink: 'https://invisible.atlassian.net/browse/POR-%ticketNumber%'
          ticketPrefix: 'POR-'
          titleRegex: '^POR-(?<ticketNumber>\d+)'
          branchRegex: '^POR-(?<ticketNumber>\d+)'
          bodyRegex: 'POR-(?<ticketNumber>\d+)'
          bodyURLRegex: 'http(s?):\/\/(invisible.atlassian.net)(\/browse)\/(POR\-)(?<ticketNumber>\d+)'
```

Note that the names need to be exactly the same on the job e.g. `jira_ticket` then in github branch rules you can set it to require that job to run.

To make it pass for all other paths (e.g. if you changing github actions or some other config and dont have a jira board for that to go) add a `fake` action by using checkout step.

```yml
# .github/workflows/ticket-check-fake
name: fake

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    paths-ignore:
      - 'libs/ui/**'
      - 'libs/flow/**'
      - 'apps/flow/**'

jobs:
  jira_ticket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  check_pr_description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

```

**Comment by jeppefrandsen** [comment]
@cyrus-za We also use a monorepo and have the same issue. For now I added support for `(?<ticketPrefix>)` (optional) in the same way as `(?<ticketNumber>)` [on our fork](https://github.com/bang-olufsen/ticket-check-action/commit/c3c5f330de37a074b5e35227e84491709cc7ea76) but not yet send it upstream.

By this you can use:

```yaml
jobs:
  check-jira-ticket:
    runs-on: ubuntu-latest
    steps:
    - name: Check JIRA ticket
      uses: bang-olufsen/ticket-check-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ticketLink: 'https://invisible.atlassian.net/browse/%ticketPrefix%-%ticketNumber%'
        ticketPrefix: '(?<ticketPrefix>\w+)-'
        titleRegex: '^(?<ticketPrefix>\w+)-(?<ticketNumber>\d+)'
```
