### ISSUE TITLE
Extracted id is wrong in updated title

### ISSUE THREAD

**Issue by watadarkstar** [neofinancial/ticket-check-action#31]
> If no ticket/issue ID is in the title, it will extract the ID from the branch or body and update the title for you. It will fail the check if no ticket ID is found anywhere.

This doesn't work properly when you use a full URL link. 

**Steps to reproduce**

1. Add the following to `.github/workflows/pull-request-linting.yml` and replace :repo and :owner with your actual repository. 

```
name: Pull Request Lint

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  title:
    name: ticket check
    runs-on: ubuntu-latest

    steps:
      - name: Check for ticket
        uses: neofinancial/ticket-check-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ticketPrefix: "#"
          bodyRegex: '#(?<ticketNumber>\d+)'
          bodyURLRegex: 'http(s?):\/\/(github.com)(\/:owner)(\/:repo)(\/issues)\/(?<ticketNumber>\d+)'
```

2. Open a pull request and in the body put:

```
Some body text 

Closes https://github.com/:owner/:repo/issues/680
```

3. Wait until the workflow finishes and the title will not have #680 in the title but instead will have some other #[id]
